name: Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      
      - name: Set up Musl
        run: |
          sudo apt-get update
          sudo apt-get install -y musl musl-tools

      - name: Build
        run: make all

      - uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "continuous"
          prerelease: true
          name: "Continuous Build"
          files: |
            cpak

      - uses: actions/upload-artifact@v4
        with:
          name: cpak
          path: |
            cpak
